### PR TITLE
fix lifetime match

### PR DESCRIPTION
**Pull request by somewheve**
Issue description:    https://github.com/suharev7/clickhouse-rs/issues/101

### CODE REVIEW

**Comment by somewheve** [comment]
```
error[E0277]: the trait bound `clickhouse_rs::pool::futures::get_handle::GetHandle: std::future::Future` is not satisfied
  --> src/ck.rs:81:30
   |
81 |             let mut client = pool.get_handle().await?;
   |                              ^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::future::Future` is not implemented for `clickhouse_rs::pool::futures::get_handle::GetHandle`
   |
   = note: required by `std::future::Future::poll`

error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
```
fix failed ~~~ Hope for your suggestion

**Comment by somewheve** [comment]
I hope use `async_trait `, but It just support the `std::future::Future`,  just not support `tokio::prelude::Future `. How can  I fix the issue?

**Comment by somewheve** [comment]
do not maintain anymore?

**Comment by suharev7** [comment]
Thank you for your contributions.

**Pull request merged**
